import 'package:intl/intl.dart';

/// Model representing a reading session log entry.
class ReadingLog {
  final String id;
  final String bookId;
  final String userId;
  final DateTime date;
  final int pagesRead;
  final int startPage;
  final int endPage;
  final DateTime createdAt;

  const ReadingLog({
    required this.id,
    required this.bookId,
    required this.userId,
    required this.date,
    required this.pagesRead,
    required this.startPage,
    required this.endPage,
    required this.createdAt,
  });

  // Date formatters
  static final DateFormat _fullDateFormat = DateFormat('EEEE, MMMM d, yyyy');
  static final DateFormat _shortDateFormat = DateFormat('MMM d, yyyy');
  static final DateFormat _dayMonthFormat = DateFormat('MMM d');
  static final DateFormat _isoDateFormat = DateFormat('yyyy-MM-dd');
  static final DateFormat _timeFormat = DateFormat('h:mm a');
  static final DateFormat _relativeFormat = DateFormat('EEEE');

  /// Get full formatted date (e.g., "Friday, November 22, 2024").
  String get formattedDateFull => _fullDateFormat.format(date);

  /// Get short formatted date (e.g., "Nov 22, 2024").
  String get formattedDateShort => _shortDateFormat.format(date);

  /// Get day and month only (e.g., "Nov 22").
  String get formattedDayMonth => _dayMonthFormat.format(date);

  /// Get ISO format date (e.g., "2024-11-22").
  String get formattedDateIso => _isoDateFormat.format(date);

  /// Get formatted created time (e.g., "3:45 PM").
  String get formattedCreatedTime => _timeFormat.format(createdAt);

  /// Get formatted created date and time.
  String get formattedCreatedAt => '${_shortDateFormat.format(createdAt)} at ${_timeFormat.format(createdAt)}';

  /// Get relative date description (Today, Yesterday, or day name).
  String get relativeDateDescription {
    final now = DateTime.now();
    final today = DateTime(now.year, now.month, now.day);
    final logDate = DateTime(date.year, date.month, date.day);
    final difference = today.difference(logDate).inDays;

    if (difference == 0) {
      return 'Today';
    } else if (difference == 1) {
      return 'Yesterday';
    } else if (difference < 7) {
      return _relativeFormat.format(date);
    } else {
      return formattedDateShort;
    }
  }

  /// Get page range string (e.g., "pages 50-75").
  String get pageRangeText => 'pages $startPage-$endPage';

  /// Get pages read summary (e.g., "25 pages read").
  String get pagesReadText => '$pagesRead ${pagesRead == 1 ? 'page' : 'pages'} read';

  /// Get detailed summary (e.g., "Read 25 pages (50-75)").
  String get detailedSummary => 'Read $pagesRead pages ($startPage-$endPage)';

  /// Create a ReadingLog from JSON map (Supabase response).
  factory ReadingLog.fromJson(Map<String, dynamic> json) {
    return ReadingLog(
      id: json['id'] as String,
      bookId: json['book_id'] as String,
      userId: json['user_id'] as String,
      date: DateTime.parse(json['date'] as String),
      pagesRead: json['pages_read'] as int? ?? 0,
      startPage: json['start_page'] as int? ?? 0,
      endPage: json['end_page'] as int? ?? 0,
      createdAt: DateTime.parse(json['created_at'] as String),
    );
  }

  /// Convert ReadingLog to JSON map for Supabase.
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'book_id': bookId,
      'user_id': userId,
      'date': _isoDateFormat.format(date),
      'pages_read': pagesRead,
      'start_page': startPage,
      'end_page': endPage,
      'created_at': createdAt.toIso8601String(),
    };
  }

  /// Convert ReadingLog to JSON map for insert (without id, timestamps auto-generated).
  Map<String, dynamic> toInsertJson() {
    return {
      'book_id': bookId,
      'user_id': userId,
      'date': _isoDateFormat.format(date),
      'pages_read': pagesRead,
      'start_page': startPage,
      'end_page': endPage,
    };
  }

  /// Create a new ReadingLog for inserting.
  /// Calculates pages_read automatically from start and end pages.
  factory ReadingLog.create({
    required String bookId,
    required String userId,
    required DateTime date,
    required int startPage,
    required int endPage,
  }) {
    return ReadingLog(
      id: '', // Will be generated by Supabase
      bookId: bookId,
      userId: userId,
      date: date,
      pagesRead: endPage - startPage,
      startPage: startPage,
      endPage: endPage,
      createdAt: DateTime.now(),
    );
  }

  /// Create a copy of ReadingLog with updated fields.
  ReadingLog copyWith({
    String? id,
    String? bookId,
    String? userId,
    DateTime? date,
    int? pagesRead,
    int? startPage,
    int? endPage,
    DateTime? createdAt,
  }) {
    return ReadingLog(
      id: id ?? this.id,
      bookId: bookId ?? this.bookId,
      userId: userId ?? this.userId,
      date: date ?? this.date,
      pagesRead: pagesRead ?? this.pagesRead,
      startPage: startPage ?? this.startPage,
      endPage: endPage ?? this.endPage,
      createdAt: createdAt ?? this.createdAt,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is ReadingLog && other.id == id;
  }

  @override
  int get hashCode => id.hashCode;

  @override
  String toString() {
    return 'ReadingLog(id: $id, bookId: $bookId, date: $formattedDateShort, pagesRead: $pagesRead)';
  }
}
